version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://www.tecnologiamex.com/api/
    ports:
      - "3001:10003"
    restart: always
