server {
    listen 10003;
    server_name localhost;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para servir archivos estáticos correctamente
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
        expires 7d;
        access_log off;
    }

    # Opcional: Manejo de errores personalizados
    error_page 404 /index.html;
}
